### ISSUE TITLE
Rename matchers to avoid core jasmine overrides

### ISSUE THREAD

**Issue by adz** [blainekasten/jasmine-enzyme#18]
Just started playing with enzyme and jasmine-enzyme and got stuck on an unexpected bug. Currently the ```toMatch``` and ```toContains``` matchers override core jasmine matchers which work on strings.

Would you consider renaming these?
They could be renamed to something like ```toMatchSelector``` and ```toContainReact``` or something like that...

Appreciate your time, and thanks for your effort and library!

**Comment by blainekasten** [comment]
Of course! I've thought about that before and not been sure if that was actually a problem or not. I'll get a new version up this afternoon.

**Comment by blainekasten** [comment]
@adz got a 1.0.0 published with the renames! Thanks for bringing this up. Also put in some code to prevent it in the future. 👍

**Comment by adz** [comment]
Great! Thanks
