### ISSUE TITLE
"not" missing in message when evaluating negative assertions

### ISSUE THREAD

**Issue by colinrcummings** [blainekasten/jasmine-enzyme#31]
I've noticed that if a negative assertion fails using one of the assertions in this library, it fails correctly but "not" is missing in the message text. For example:

##### Component:
    import React from 'react';

    class Fail extends React.Component {
      render () {
        return (
          <div>
            <input id="checked" checked={true} />
            <input id="not" checked={true} />
          </div>
        );
      }
    }

    module.exports = Fail;

##### Spec:
    import React from 'react';
    import {mount} from 'enzyme';
    import jasmineEnzyme from 'jasmine-enzyme';
    var Fail= require('../Fail.jsx');

    describe('Fail', () => {
      var wrapper;

      beforeEach(() => {
        jasmineEnzyme();
        wrapper = mount(<Fail />);
      });

      it('should render the not checked component as not checked', () => {
        expect(wrapper.find('#not')).not.toBeChecked();
      });
    });

##### Result:
    F

    Failures:
    1) Fail should render the not checked component as not checked
      Message:
        Expected "<input id="not" name="">" to be checked

The message should be "Expected [emement] **not** to be checked".

**Comment by blainekasten** [comment]
Interesting. I assumed jasmine handled this for me. I'd be excited to see a PR for this if you have the free time. Otherwise i'll try and get to it soon

**Comment by blainekasten** [comment]
I started working on this in branch `EnhanceNegatedMessages`. I'll slowly keep working on it for a while until it's done. It's a lot of monotonous work so it probably won't happen quickly. If anyone wants to take it over and finish it, that'd be awesome! Otherwise it'll finish eventually ;)

**Comment by blainekasten** [comment]
This is now released in 1.2.0 🎉
