### ISSUE TITLE
Installation instructions are vague

### ISSUE THREAD

**Issue by carlbaron** [blainekasten/jasmine-enzyme#32]
I was excited to try out this library but I ran into a lot of trouble installing and configuring.

I did get it working but I think others may have some difficulty too. I'm happy to make a PR with some more detailed installation instructions if it would be helpful.

**Comment by blainekasten** [comment]
A PR would be awesome for anything you think that could be clearer!

**Comment by carlbaron** [comment]
@blainekasten Cool! I made a small PR, see #33. I've been using Jest for a while but I'm brand new to Enzyme. The enzyme docs brought me here so maybe I missed some steps that their documentation would have made clear, but I think it will help some people to see everything laid out in the `jasmine-enzyme` docs as well.

I think it may be helpful to provide a complete example project as well so newbies can see a complete, working configuration. Let me know if you think that's a good idea and I'll make a PR.

**Comment by blainekasten** [comment]
I'm sort of on the fence of the example project. This library isn't that complicated that I wouldn't want to conflate the codebase for little benefit. But I'm not against it either. If you think it would help and could put together a minimal code use I _might_ be interested.

For now i'm going to close this issue as we merged the original issue

**Comment by carlbaron** [comment]
OK cool, after thinking about it more I agree, an example project is probably too much at this point.
